name: chooshi
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.5.1
  scroll_to_index: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  flutter_native_splash: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint:
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/chooshi_splash.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/chooshi_ic.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/chooshi_ic_foreground.png'

flutter:
  uses-material-design: true
